CREATE TABLE TIPOUTILITARIO (
  codTipoUtilitario INT NOT NULL AUTO_INCREMENT,
  tipoUtilitario VARCHAR NULL,
  PRIMARY KEY(codTipoUtilitario)
)
CHECKSUM = 1
PACK_KEYS = 1;

CREATE TABLE UTILITARIOS (
  codUtililtario INT NOT NULL AUTO_INCREMENT,
  utilitario VARCHAR NULL,
  codtiUtilitario INT UNSIGNED ZEROFILL NULL,
  PRIMARY KEY(codUtililtario)
)
CHECKSUM = 1
PACK_KEYS = 1;


